CREATE TABLE [dbo].[GRN] (
    [GRNId]              INT              IDENTITY (1, 1) NOT NULL,
    [GRNDate]            DATE             NULL,
    [LOTNo]              VARCHAR (50)     NULL,
    [SupplierId]         INT              NULL,
    [RMId]               INT              NULL,
    [Height]             DECIMAL (10, 2)  NULL,
    [HeightUOM]          INT              NULL,
    [Width]              DECIMAL (10, 2)  NULL,
    [WidthUOM]           INT              NOT NULL,
    [Thick]              DECIMAL (10, 2)  NULL,
    [ThickUOM]           INT              NULL,
    [Wgt]                DECIMAL (10, 2)  NULL,
    [Roll]               INT              NULL,
    [RollUOM]            INT              NULL,
    [DOM]                DATE             NULL,
    [DONo]               VARCHAR (50)     NULL,
    [STNCustomId]        INT              NULL,
    [ComponentId]        INT              NULL,
    [KASWgt]             DECIMAL (10, 2)  NULL,
    [DutyImp]            DECIMAL (18, 2)  NULL,
    [GST]                DECIMAL (18, 2)  NULL,
    [CIF]                DECIMAL (18, 2)  NULL,
    [CustomDate]         DATE             NULL,
    [CustomNo]           VARCHAR (50)     NULL,
    [InvoiceNo]          VARCHAR (50)     NULL,
    [CurrencyId]         INT              NULL,
    [AmountCurrency]     DECIMAL (18, 2)  NULL,
    [ExRate]             DECIMAL (24, 14) NULL,
    [Amount]             DECIMAL (18, 2)  NULL,
    [PONo]               VARCHAR (50)     NULL,
    [OTDLate]            VARCHAR (10)     NULL,
    [FwdInvNo]           VARCHAR (50)     NULL,
    [AMT]                DECIMAL (18, 2)  NULL,
    [Forwarder]          NVARCHAR (50)    NULL,
    [DocRefNo]           VARCHAR (50)     NULL,
    [VCARNo]             VARCHAR (50)     NULL,
    [ImpFreight]         DECIMAL (18, 2)  NULL,
    [CurrencyAdj]        VARCHAR (50)     NULL,
    [TermChrg]           DECIMAL (18, 2)  NULL,
    [AprtTxFee]          DECIMAL (18, 2)  NULL,
    [Delivery]           DECIMAL (18, 2)  NULL,
    [HandFwd]            DECIMAL (18, 2)  NULL,
    [CustomExamFee]      DECIMAL (18, 2)  NULL,
    [CollectFee]         DECIMAL (18, 2)  NULL,
    [CargoPrmt]          VARCHAR (50)     NULL,
    [DocFee]             DECIMAL (18, 2)  NULL,
    [BreakBulk]          DECIMAL (18, 2)  NULL,
    [EDIFee]             DECIMAL (18, 2)  NULL,
    [FreightGST]         DECIMAL (18, 2)  NULL,
    [TotalFreightCost]   DECIMAL (18, 2)  NULL,
    [TotalFreightRMCost] DECIMAL (18, 2)  NULL,
    [CreatedByUserId]    INT              NULL,
    [CreatedDT]          DATETIME         NULL,
    [EditedByUserId]     INT              NULL,
    [EditedDT]           DATETIME         NULL,
    CONSTRAINT [PK_GrnLog] PRIMARY KEY CLUSTERED ([GRNId] ASC)
);





