CREATE TABLE [dbo].[GRN] (
    [GRNId]              INT              IDENTITY (1, 1) NOT NULL,
    [GRNDate]            DATE             NULL,
    [DailyNo]            INT              NULL,
    [GRNCode]            VARCHAR (50)     NULL,
    [LOTNo]              VARCHAR (50)     NULL,
    [SupplierId]         INT              NULL,
    [RMId]               INT              NULL,
    [SizeCount]          INT              NULL,
    [Height_1]           DECIMAL (10, 2)  NULL,
    [HeightUOM_1]        INT              NULL,
    [Width_1]            DECIMAL (10, 2)  NULL,
    [WidthUOM_1]         INT              NULL,
    [Thick_1]            DECIMAL (10, 2)  NULL,
    [ThickUOM_1]         INT              NULL,
    [Wgt_1]              DECIMAL (10, 2)  NULL,
    [Roll_1]             INT              NULL,
    [RollUOM_1]          INT              NULL,
    [Height_2]           DECIMAL (10, 2)  NULL,
    [HeightUOM_2]        INT              NULL,
    [Width_2]            DECIMAL (10, 2)  NULL,
    [WidthUOM_2]         INT              NULL,
    [Thick_2]            DECIMAL (10, 2)  NULL,
    [ThickUOM_2]         INT              NULL,
    [Wgt_2]              DECIMAL (10, 2)  NULL,
    [Roll_2]             INT              NULL,
    [RollUOM_2]          INT              NULL,
    [Height_3]           DECIMAL (10, 2)  NULL,
    [HeightUOM_3]        INT              NULL,
    [Width_3]            DECIMAL (10, 2)  NULL,
    [WidthUOM_3]         INT              NULL,
    [Thick_3]            DECIMAL (10, 2)  NULL,
    [ThickUOM_3]         INT              NULL,
    [Wgt_3]              DECIMAL (10, 2)  NULL,
    [Roll_3]             INT              NULL,
    [RollUOM_3]          INT              NULL,
    [Height_4]           DECIMAL (10, 2)  NULL,
    [HeightUOM_4]        INT              NULL,
    [Width_4]            DECIMAL (10, 2)  NULL,
    [WidthUOM_4]         INT              NULL,
    [Thick_4]            DECIMAL (10, 2)  NULL,
    [ThickUOM_4]         INT              NULL,
    [Wgt_4]              DECIMAL (10, 2)  NULL,
    [Roll_4]             INT              NULL,
    [RollUOM_4]          INT              NULL,
    [Height_5]           DECIMAL (10, 2)  NULL,
    [HeightUOM_5]        INT              NULL,
    [Width_5]            DECIMAL (10, 2)  NULL,
    [WidthUOM_5]         INT              NULL,
    [Thick_5]            DECIMAL (10, 2)  NULL,
    [ThickUOM_5]         INT              NULL,
    [Wgt_5]              DECIMAL (10, 2)  NULL,
    [Roll_5]             INT              NULL,
    [RollUOM_5]          INT              NULL,
    [Height_6]           DECIMAL (10, 2)  NULL,
    [HeightUOM_6]        INT              NULL,
    [Width_6]            DECIMAL (10, 2)  NULL,
    [WidthUOM_6]         INT              NULL,
    [Thick_6]            DECIMAL (10, 2)  NULL,
    [ThickUOM_6]         INT              NULL,
    [Wgt_6]              DECIMAL (10, 2)  NULL,
    [Roll_6]             INT              NULL,
    [RollUOM_6]          INT              NULL,
    [Height_7]           DECIMAL (10, 2)  NULL,
    [HeightUOM_7]        INT              NULL,
    [Width_7]            DECIMAL (10, 2)  NULL,
    [WidthUOM_7]         INT              NULL,
    [Thick_7]            DECIMAL (10, 2)  NULL,
    [ThickUOM_7]         INT              NULL,
    [Wgt_7]              DECIMAL (10, 2)  NULL,
    [Roll_7]             INT              NULL,
    [RollUOM_7]          INT              NULL,
    [Height_8]           DECIMAL (10, 2)  NULL,
    [HeightUOM_8]        INT              NULL,
    [Width_8]            DECIMAL (10, 2)  NULL,
    [WidthUOM_8]         INT              NULL,
    [Thick_8]            DECIMAL (10, 2)  NULL,
    [ThickUOM_8]         INT              NULL,
    [Wgt_8]              DECIMAL (10, 2)  NULL,
    [Roll_8]             INT              NULL,
    [RollUOM_8]          INT              NULL,
    [Height_9]           DECIMAL (10, 2)  NULL,
    [HeightUOM_9]        INT              NULL,
    [Width_9]            DECIMAL (10, 2)  NULL,
    [WidthUOM_9]         INT              NULL,
    [Thick_9]            DECIMAL (10, 2)  NULL,
    [ThickUOM_9]         INT              NULL,
    [Wgt_9]              DECIMAL (10, 2)  NULL,
    [Roll_9]             INT              NULL,
    [RollUOM_9]          INT              NULL,
    [Height_10]          DECIMAL (10, 2)  NULL,
    [HeightUOM_10]       INT              NULL,
    [Width_10]           DECIMAL (10, 2)  NULL,
    [WidthUOM_10]        INT              NULL,
    [Thick_10]           DECIMAL (10, 2)  NULL,
    [ThickUOM_10]        INT              NULL,
    [Wgt_10]             DECIMAL (10, 2)  NULL,
    [Roll_10]            INT              NULL,
    [RollUOM_10]         INT              NULL,
    [Height_11]          DECIMAL (10, 2)  NULL,
    [HeightUOM_11]       INT              NULL,
    [Width_11]           DECIMAL (10, 2)  NULL,
    [WidthUOM_11]        INT              NULL,
    [Thick_11]           DECIMAL (10, 2)  NULL,
    [ThickUOM_11]        INT              NULL,
    [Wgt_11]             DECIMAL (10, 2)  NULL,
    [Roll_11]            INT              NULL,
    [RollUOM_11]         INT              NULL,
    [Height_12]          DECIMAL (10, 2)  NULL,
    [HeightUOM_12]       INT              NULL,
    [Width_12]           DECIMAL (10, 2)  NULL,
    [WidthUOM_12]        INT              NULL,
    [Thick_12]           DECIMAL (10, 2)  NULL,
    [ThickUOM_12]        INT              NULL,
    [Wgt_12]             DECIMAL (10, 2)  NULL,
    [Roll_12]            INT              NULL,
    [RollUOM_12]         INT              NULL,
    [Height_13]          DECIMAL (10, 2)  NULL,
    [HeightUOM_13]       INT              NULL,
    [Width_13]           DECIMAL (10, 2)  NULL,
    [WidthUOM_13]        INT              NULL,
    [Thick_13]           DECIMAL (10, 2)  NULL,
    [ThickUOM_13]        INT              NULL,
    [Wgt_13]             DECIMAL (10, 2)  NULL,
    [Roll_13]            INT              NULL,
    [RollUOM_13]         INT              NULL,
    [Height_14]          DECIMAL (10, 2)  NULL,
    [HeightUOM_14]       INT              NULL,
    [Width_14]           DECIMAL (10, 2)  NULL,
    [WidthUOM_14]        INT              NULL,
    [Thick_14]           DECIMAL (10, 2)  NULL,
    [ThickUOM_14]        INT              NULL,
    [Wgt_14]             DECIMAL (10, 2)  NULL,
    [Roll_14]            INT              NULL,
    [RollUOM_14]         INT              NULL,
    [Height_15]          DECIMAL (10, 2)  NULL,
    [HeightUOM_15]       INT              NULL,
    [Width_15]           DECIMAL (10, 2)  NULL,
    [WidthUOM_15]        INT              NULL,
    [Thick_15]           DECIMAL (10, 2)  NULL,
    [ThickUOM_15]        INT              NULL,
    [Wgt_15]             DECIMAL (10, 2)  NULL,
    [Roll_15]            INT              NULL,
    [RollUOM_15]         INT              NULL,
    [DOM]                DATE             NULL,
    [DONo]               VARCHAR (50)     NULL,
    [STNCustomId]        INT              NULL,
    [ComponentId]        INT              NULL,
    [KASWgt]             DECIMAL (10, 2)  NULL,
    [DutyImp]            DECIMAL (18, 2)  NULL,
    [GST]                DECIMAL (18, 2)  NULL,
    [CIF]                DECIMAL (18, 2)  NULL,
    [CustomDate]         DATE             NULL,
    [CustomNo]           VARCHAR (50)     NULL,
    [DutyExcise]         DECIMAL (18, 2)  NULL,
    [InvoiceNo]          VARCHAR (50)     NULL,
    [CurrencyId]         INT              NULL,
    [AmountCurrency]     DECIMAL (18, 2)  NULL,
    [ExRate]             DECIMAL (24, 14) NULL,
    [Amount]             DECIMAL (18, 2)  NULL,
    [PONo]               VARCHAR (50)     NULL,
    [OTDLate]            VARCHAR (10)     NULL,
    [FwdInvNo]           VARCHAR (50)     NULL,
    [AMT]                DECIMAL (18, 2)  NULL,
    [Forwarder]          NVARCHAR (50)    NULL,
    [DocRefNo]           VARCHAR (50)     NULL,
    [VCARNo]             VARCHAR (50)     NULL,
    [ImpFreight]         DECIMAL (18, 2)  NULL,
    [CurrencyAdj]        VARCHAR (50)     NULL,
    [TermChrg]           DECIMAL (18, 2)  NULL,
    [AprtTxFee]          DECIMAL (18, 2)  NULL,
    [Delivery]           DECIMAL (18, 2)  NULL,
    [HandFwd]            DECIMAL (18, 2)  NULL,
    [CustomExamFee]      DECIMAL (18, 2)  NULL,
    [CollectFee]         DECIMAL (18, 2)  NULL,
    [CargoPrmt]          VARCHAR (50)     NULL,
    [DocFee]             DECIMAL (18, 2)  NULL,
    [BreakBulk]          DECIMAL (18, 2)  NULL,
    [EDIFee]             DECIMAL (18, 2)  NULL,
    [FreightGST]         DECIMAL (18, 2)  NULL,
    [TotalFreightCost]   DECIMAL (18, 2)  NULL,
    [TotalFreightRMCost] DECIMAL (18, 2)  NULL,
    [CreatedByUserId]    INT              NULL,
    [CreatedDT]          DATETIME         NULL,
    [EditedByUserId]     INT              NULL,
    [EditedDT]           DATETIME         NULL,
    CONSTRAINT [PK_GrnLog] PRIMARY KEY CLUSTERED ([GRNId] ASC)
);












GO



CREATE TRIGGER [dbo].[GRN_Insert]
       ON [dbo].[GRN]
AFTER INSERT
AS
BEGIN
SET NOCOUNT ON;
   
DECLARE @RptYear AS INT,
@DailyNo AS INT,
@GRNId AS INT
 
SELECT @RptYear = YEAR(GRNDate), @GRNId = GRNId
FROM inserted 

SELECT @DailyNo = MAX(ISNULL(DailyNo,0))
FROM GRN WITH (NOLOCK)
WHERE YEAR(GRNDate) = @RptYear

UPDATE GRN 
SET DailyNo = ISNULL(@DailyNo,0)+1, GRNCode =  RIGHT(YEAR(GRNDate), 2) + RIGHT(CONCAT('000', ISNULL(@DailyNo,0)+1), 3)
WHERE GRNId = @GRNId 
END