CREATE TABLE [dbo].[RptLG] (
    [RptId]                 INT             IDENTITY (1, 1) NOT NULL,
    [RptStatusId]           INT             NULL,
    [RptY1]                 INT             NULL,
    [RptY2]                 INT             NULL,
    [RptSDate_Y1]           DATE            NULL,
    [RptEDate_Y1]           DATE            NULL,
    [RptSDate_Y2]           DATE            NULL,
    [RptEDate_Y2]           DATE            NULL,
    [RptSDate_Y3]           DATE            NULL,
    [RptEDate_Y3]           DATE            NULL,
    [RefNo]                 VARCHAR (20)    NULL,
    [LDate]                 DATETIME        NULL,
    [LRcptDept]             NVARCHAR (50)   NULL,
    [LRcptBr]               NVARCHAR (50)   NULL,
    [LRcptAdd1]             NVARCHAR (100)  NULL,
    [LRcptAdd2]             NVARCHAR (100)  NULL,
    [LRcptAdd3]             NVARCHAR (100)  NULL,
    [LRcptAdd4]             NVARCHAR (100)  NULL,
    [PBBCekNo]              NVARCHAR (50)   NULL,
    [LicenseFee]            NCHAR (10)      NULL,
    [LocImpM_Y1]            NVARCHAR (50)   NULL,
    [LocImpM_Y2]            NVARCHAR (50)   NULL,
    [LocExpM_Y1]            NVARCHAR (50)   NULL,
    [LocExpM_Y2]            NVARCHAR (50)   NULL,
    [SignedByEmpId]         INT             NULL,
    [F_SignedByPos]         NVARCHAR (50)   NULL,
    [F_SignedByName]        NVARCHAR (50)   NULL,
    [F_SignedByIDNo]        VARCHAR (20)    NULL,
    [SignedDate]            DATE            NULL,
    [BRcptDept]             NVARCHAR (50)   NULL,
    [BRcptBr]               NVARCHAR (50)   NULL,
    [BRcptAdd1]             NVARCHAR (100)  NULL,
    [BRcptAdd2]             NVARCHAR (100)  NULL,
    [BRcptAdd3]             NVARCHAR (100)  NULL,
    [BRcptAdd4]             NVARCHAR (100)  NULL,
    [F_BSignedByPos]        NVARCHAR (50)   NULL,
    [F_BSignedByName]       NVARCHAR (50)   NULL,
    [F_BSignedByIDNo]       VARCHAR (20)    NULL,
    [F_BSignedByAdd1]       NVARCHAR (100)  NULL,
    [F_BSignedByAdd2]       NVARCHAR (100)  NULL,
    [F_BSignedByAdd3]       NVARCHAR (100)  NULL,
    [F_BSignedByAdd4]       NVARCHAR (100)  NULL,
    [MfdGood]               NVARCHAR (MAX)  NULL,
    [MfdLicenseSDate]       DATE            NULL,
    [MfdLicenseEDate]       DATE            NULL,
    [IsChgCoName]           BIT             NULL,
    [IsChgCoMember]         BIT             NULL,
    [IsChgAddress]          BIT             NULL,
    [IsChgFtyStr]           BIT             NULL,
    [IsChgEq]               BIT             NULL,
    [F_RMCost]              DECIMAL (18, 2) NULL,
    [BgtRMCost]             DECIMAL (18, 2) NULL,
    [F_RdyGoodCost]         DECIMAL (18, 2) NULL,
    [BgtRdyGoodCost]        DECIMAL (18, 2) NULL,
    [F_MktExpCost]          DECIMAL (18, 2) NULL,
    [MktExpRate]            DECIMAL (5, 2)  NULL,
    [BgtMktExpCost]         DECIMAL (18, 2) NULL,
    [BgtMktExpRate]         DECIMAL (5, 2)  NULL,
    [F_LocalSalesCost]      DECIMAL (18, 2) NULL,
    [LocalSalesRate]        DECIMAL (5, 2)  NULL,
    [BgtLocSalesCost]       DECIMAL (18, 2) NULL,
    [BgtLocSalesRate]       DECIMAL (5, 2)  NULL,
    [IPC_RDC]               NVARCHAR (200)  NULL,
    [ValueAdded]            NVARCHAR (200)  NULL,
    [RepairSvc]             NVARCHAR (200)  NULL,
    [SparePart]             NVARCHAR (200)  NULL,
    [F_Imp_OpenBalWgt_Y1]   DECIMAL (10, 2) NULL,
    [F_Imp_OpenBalCost_Y1]  DECIMAL (18, 2) NULL,
    [F_Imp_ImpRMWgt_Y1]     DECIMAL (10, 2) NULL,
    [F_Imp_ImpRMCost_Y1]    DECIMAL (18, 2) NULL,
    [F_Imp_LocRMWgt_Y1]     DECIMAL (10, 2) NULL,
    [F_Imp_LocRMCost_Y1]    DECIMAL (18, 2) NULL,
    [F_Imp_UsedRMWgt_Y1]    DECIMAL (10, 2) NULL,
    [F_Imp_UsedRMCost_Y1]   DECIMAL (18, 2) NULL,
    [F_Imp_ReturnedWgt_Y1]  DECIMAL (10, 2) NULL,
    [F_Imp_CloseBalWgt_Y1]  DECIMAL (10, 2) NULL,
    [F_Imp_CloseBalCost_Y1] DECIMAL (18, 2) NULL,
    [F_Imp_OpenBalWgt_Y2]   DECIMAL (10, 2) NULL,
    [F_Imp_OpenBalCost_Y2]  DECIMAL (18, 2) NULL,
    [F_ImpRMWgt_Y2]         DECIMAL (10, 2) NULL,
    [F_ImpRMCost_Y2]        DECIMAL (18, 2) NULL,
    [F_Imp_LocRMWgt_Y2]     DECIMAL (10, 2) NULL,
    [F_Imp_LocRMCost_Y2]    DECIMAL (18, 2) NULL,
    [F_Imp_UsedRMWgt_Y2]    DECIMAL (10, 2) NULL,
    [F_Imp_UsedRMCost_Y2]   DECIMAL (18, 2) NULL,
    [F_Imp_ReturnedWgt_Y2]  DECIMAL (10, 2) NULL,
    [F_Imp_CloseBalWgt_Y2]  DECIMAL (10, 2) NULL,
    [F_Imp_CloseBalCost_Y2] DECIMAL (18, 2) NULL,
    [F_Rdy_Cost_Y1]         DECIMAL (18, 2) NULL,
    [F_Rdy_DutyImpCost_Y1]  DECIMAL (18, 2) NULL,
    [F_Rdy_GSTCost_Y1]      DECIMAL (18, 2) NULL,
    [F_Rdy_TaxCost_Y1]      DECIMAL (18, 2) NULL,
    [F_Rdy_Cost_Y3]         DECIMAL (18, 2) NULL,
    [F_Rdy_DutyImpCost_Y3]  DECIMAL (18, 2) NULL,
    [F_Rdy_GSTCost_Y3]      DECIMAL (18, 2) NULL,
    [F_Rdy_TaxCost_Y3]      DECIMAL (18, 2) NULL,
    [F_Rdy_StkCost_Y2]      DECIMAL (18, 2) NULL,
    [F_Rdy_DutyImpCost_Y2]  DECIMAL (18, 2) NULL,
    [F_Rdy_GSTCost_Y2]      DECIMAL (18, 2) NULL,
    [F_Rdy_TaxCost_Y2]      DECIMAL (18, 2) NULL,
    [F_Bgt_Qty_Loc]         INT             NULL,
    [F_Bgt_Cost_Loc]        DECIMAL (18, 2) NULL,
    [F_Bgt_DutyImpCost_Loc] DECIMAL (18, 2) NULL,
    [F_Bgt_GSTCost_Loc]     DECIMAL (18, 2) NULL,
    [F_Bgt_TaxCost_Loc]     DECIMAL (18, 2) NULL,
    [F_Bgt_Qty_Imp]         INT             NULL,
    [F_Bgt_Cost_Imp]        DECIMAL (18, 2) NULL,
    [F_Bgt_DutyImpCost_Imp] DECIMAL (18, 2) NULL,
    [F_Bgt_GSTCost_Imp]     DECIMAL (18, 2) NULL,
    [F_Bgt_TaxCost_Imp]     DECIMAL (18, 2) NULL,
    [CreatedByUserId]       INT             NULL,
    [CreatedDT]             DATETIME        NULL,
    [EditedByUserId]        INT             NULL,
    [EditedDT]              DATETIME        NULL,
    CONSTRAINT [PK_RptLG] PRIMARY KEY CLUSTERED ([RptId] ASC)
);

