CREATE TABLE [dbo].[RptLG] (
    [RptId]                 INT             IDENTITY (1, 1) NOT NULL,
    [RptStatusId]           INT             NULL,
    [F_CoName]              NVARCHAR (50)   NULL,
    [F_CoRegNo]             VARCHAR (20)    NULL,
    [F_CoAdd1]              NVARCHAR (100)  NULL,
    [F_CoAdd2]              NVARCHAR (100)  NULL,
    [F_CoAdd3]              NVARCHAR (100)  NULL,
    [F_CoAdd4]              NVARCHAR (100)  NULL,
    [F_CoTel]               VARCHAR (20)    NULL,
    [F_CoFax]               VARCHAR (20)    NULL,
    [F_CoEmail]             VARCHAR (20)    NULL,
    [F_CoWebsite]           NVARCHAR (50)   NULL,
    [F_CoLogo]              VARCHAR (50)    NULL,
    [RptY1]                 INT             NULL,
    [RptY2]                 INT             NULL,
    [RptSDate_Y1]           DATE            NULL,
    [RptEDate_Y1]           DATE            NULL,
    [RptSDate_Y2]           DATE            NULL,
    [RptEDate_Y2]           DATE            NULL,
    [RptSDate_Y3]           DATE            NULL,
    [RptEDate_Y3]           DATE            NULL,
    [RefNo]                 VARCHAR (50)    NULL,
    [LDate]                 DATETIME        NULL,
    [LRcptDept]             NVARCHAR (50)   NULL,
    [LRcptBr]               NVARCHAR (50)   NULL,
    [LRcptAdd1]             NVARCHAR (100)  NULL,
    [LRcptAdd2]             NVARCHAR (100)  NULL,
    [LRcptAdd3]             NVARCHAR (100)  NULL,
    [LRcptAdd4]             NVARCHAR (100)  NULL,
    [PBBCekNo]              NVARCHAR (50)   NULL,
    [LicenseFee]            DECIMAL (18, 2) NULL,
    [SignedByEmpId]         INT             NULL,
    [SignedByPos]           NVARCHAR (50)   NULL,
    [SignedByName]          NVARCHAR (50)   NULL,
    [SignedDate]            DATE            NULL,
    [AppByEmpId]            INT             NULL,
    [AppByPos]              NVARCHAR (50)   NULL,
    [AppByName]             NVARCHAR (50)   NULL,
    [AppByIDNo]             VARCHAR (20)    NULL,
    [AppCoName]             NVARCHAR (50)   NULL,
    [AppAdd1]               NVARCHAR (100)  NULL,
    [AppAdd2]               NVARCHAR (100)  NULL,
    [AppAdd3]               NVARCHAR (100)  NULL,
    [AppAdd4]               NVARCHAR (100)  NULL,
    [AppDate]               DATE            NULL,
    [BRcptDept]             NVARCHAR (50)   NULL,
    [BRcptBr]               NVARCHAR (50)   NULL,
    [BRcptAdd1]             NVARCHAR (100)  NULL,
    [BRcptAdd2]             NVARCHAR (100)  NULL,
    [BRcptAdd3]             NVARCHAR (100)  NULL,
    [BRcptAdd4]             NVARCHAR (100)  NULL,
    [RptCoName]             NVARCHAR (50)   NULL,
    [RptSignedByEmpId]      INT             NULL,
    [RptSignedByPos]        NVARCHAR (50)   NULL,
    [RptSignedByIDNo]       VARCHAR (20)    NULL,
    [RptSignedByName]       NVARCHAR (50)   NULL,
    [MfdGoodY1]             NVARCHAR (MAX)  NULL,
    [MfdGoodY2]             NVARCHAR (MAX)  NULL,
    [MfdGoodY3]             NVARCHAR (MAX)  NULL,
    [MfdLicenseSDate]       DATE            NULL,
    [MfdLicenseEDate]       DATE            NULL,
    [IsChgCoName]           BIT             NULL,
    [IsChgCoMember]         BIT             NULL,
    [IsChgAddress]          BIT             NULL,
    [IsChgFtyStr]           BIT             NULL,
    [IsChgEq]               BIT             NULL,
    [F_RMCost]              DECIMAL (18, 2) NULL,
    [BgtRMCost]             DECIMAL (18, 2) NULL,
    [F_RdyGoodCost]         DECIMAL (18, 2) NULL,
    [BgtRdyGoodCost]        DECIMAL (18, 2) NULL,
    [F_MktExpCost]          DECIMAL (18, 2) NULL,
    [MktExpRate]            DECIMAL (5, 2)  NULL,
    [BgtMktExpCost]         DECIMAL (18, 2) NULL,
    [BgtMktExpRate]         DECIMAL (5, 2)  NULL,
    [F_LocalSalesCost]      DECIMAL (18, 2) NULL,
    [LocalSalesRate]        DECIMAL (5, 2)  NULL,
    [BgtLocSalesCost]       DECIMAL (18, 2) NULL,
    [BgtLocSalesRate]       DECIMAL (5, 2)  NULL,
    [IPC_RDC]               NVARCHAR (200)  NULL,
    [ValueAdded]            NVARCHAR (200)  NULL,
    [RepairSvc]             NVARCHAR (200)  NULL,
    [SparePart]             NVARCHAR (200)  NULL,
    [F_Imp_OpenBalWgt_Y1]   DECIMAL (10, 2) NULL,
    [F_Imp_OpenBalCost_Y1]  DECIMAL (18, 2) NULL,
    [F_Imp_ImpRMWgt_Y1]     DECIMAL (10, 2) NULL,
    [F_Imp_ImpRMCost_Y1]    DECIMAL (18, 2) NULL,
    [F_Imp_LocRMWgt_Y1]     DECIMAL (10, 2) NULL,
    [F_Imp_LocRMCost_Y1]    DECIMAL (18, 2) NULL,
    [F_Imp_UsedRMWgt_Y1]    DECIMAL (10, 2) NULL,
    [F_Imp_UsedRMCost_Y1]   DECIMAL (18, 2) NULL,
    [F_Imp_ReturnedWgt_Y1]  DECIMAL (10, 2) NULL,
    [F_Imp_CloseBalWgt_Y1]  DECIMAL (10, 2) NULL,
    [F_Imp_CloseBalCost_Y1] DECIMAL (18, 2) NULL,
    [F_Imp_OpenBalWgt_Y2]   DECIMAL (10, 2) NULL,
    [F_Imp_OpenBalCost_Y2]  DECIMAL (18, 2) NULL,
    [F_ImpRMWgt_Y2]         DECIMAL (10, 2) NULL,
    [F_ImpRMCost_Y2]        DECIMAL (18, 2) NULL,
    [F_Imp_LocRMWgt_Y2]     DECIMAL (10, 2) NULL,
    [F_Imp_LocRMCost_Y2]    DECIMAL (18, 2) NULL,
    [F_Imp_UsedRMWgt_Y2]    DECIMAL (10, 2) NULL,
    [F_Imp_UsedRMCost_Y2]   DECIMAL (18, 2) NULL,
    [F_Imp_ReturnedWgt_Y2]  DECIMAL (10, 2) NULL,
    [F_Imp_CloseBalWgt_Y2]  DECIMAL (10, 2) NULL,
    [F_Imp_CloseBalCost_Y2] DECIMAL (18, 2) NULL,
    [F_Exp_OpenBalQty_Y1]   DECIMAL (10, 2) NULL,
    [F_Exp_OpenBalCost_Y1]  DECIMAL (18, 2) NULL,
    [F_Exp_MadeQty_Y1]      DECIMAL (10, 2) NULL,
    [F_Exp_MadeCost_Y1]     DECIMAL (18, 2) NULL,
    [F_Exp_Qty_Y1]          DECIMAL (10, 2) NULL,
    [F_Exp_Cost_Y1]         DECIMAL (18, 2) NULL,
    [F_Exp_LocSalesQty_Y1]  DECIMAL (10, 2) NULL,
    [F_Exp_LocSalesCost_Y1] DECIMAL (18, 2) NULL,
    [F_Exp_DamagedQty_Y1]   DECIMAL (10, 2) NULL,
    [F_Exp_DamagedCost_Y1]  DECIMAL (18, 2) NULL,
    [F_Exp_CloseQty_Y1]     DECIMAL (10, 2) NULL,
    [F_Exp_CloseCost_Y1]    DECIMAL (18, 2) NULL,
    [F_Exp_OpenBalQty_Y2]   DECIMAL (10, 2) NULL,
    [F_Exp_OpenBalCost_Y2]  DECIMAL (18, 2) NULL,
    [F_Exp_MadeQty_Y2]      DECIMAL (10, 2) NULL,
    [F_Exp_MadeCost_Y2]     DECIMAL (18, 2) NULL,
    [F_Exp_Qty_Y2]          DECIMAL (10, 2) NULL,
    [F_Exp_Cost_Y2]         DECIMAL (18, 2) NULL,
    [F_Exp_LocSalesQty_Y2]  DECIMAL (10, 2) NULL,
    [F_Exp_LocSalesCost_Y2] DECIMAL (18, 2) NULL,
    [F_Exp_DamagedQty_Y2]   DECIMAL (10, 2) NULL,
    [F_Exp_DamagedCost_Y2]  DECIMAL (18, 2) NULL,
    [F_Exp_CloseQty_Y2]     DECIMAL (10, 2) NULL,
    [F_Exp_CloseCost_Y2]    DECIMAL (18, 2) NULL,
    [F_Rdy_Cost]            DECIMAL (18, 2) NULL,
    [F_Rdy_DutyImpCost]     DECIMAL (18, 2) NULL,
    [F_Rdy_GSTCost]         DECIMAL (18, 2) NULL,
    [F_Rdy_TaxCost]         DECIMAL (18, 2) NULL,
    [F_Bgt_Qty_Loc]         INT             NULL,
    [F_Bgt_Cost_Loc]        DECIMAL (18, 2) NULL,
    [F_Bgt_DutyImpCost_Loc] DECIMAL (18, 2) NULL,
    [F_Bgt_GSTCost_Loc]     DECIMAL (18, 2) NULL,
    [F_Bgt_TaxCost_Loc]     DECIMAL (18, 2) NULL,
    [F_Bgt_Qty_Imp]         INT             NULL,
    [F_Bgt_Cost_Imp]        DECIMAL (18, 2) NULL,
    [F_Bgt_DutyImpCost_Imp] DECIMAL (18, 2) NULL,
    [F_Bgt_GSTCost_Imp]     DECIMAL (18, 2) NULL,
    [F_Bgt_TaxCost_Imp]     DECIMAL (18, 2) NULL,
    [CreatedByUserId]       INT             NULL,
    [CreatedDT]             DATETIME        NULL,
    [EditedByUserId]        INT             NULL,
    [EditedDT]              DATETIME        NULL,
    CONSTRAINT [PK_RptLG_1] PRIMARY KEY CLUSTERED ([RptId] ASC)
);





























