CREATE TABLE [dbo].[RptSK] (
    [RptId]            INT             IDENTITY (1, 1) NOT NULL,
    [RptStatusId]      INT             NULL,
    [RptDate]          DATETIME        NULL,
    [RptMth]           INT             NULL,
    [RptYr]            INT             NULL,
    [RefNo]            VARCHAR (20)    NULL,
    [LetterDate]       DATETIME        NULL,
    [LRcptDept]        NVARCHAR (50)   NULL,
    [LRcptBr]          NVARCHAR (50)   NULL,
    [LRcptAdd1]        NVARCHAR (100)  NULL,
    [LRcptAdd2]        NVARCHAR (100)  NULL,
    [LRcptAdd3]        NVARCHAR (100)  NULL,
    [LRcptAdd4]        NVARCHAR (100)  NULL,
    [SignedByEmpId]    INT             NULL,
    [F_SignedByPos]    NVARCHAR (50)   NULL,
    [F_SignedByName]   NVARCHAR (50)   NULL,
    [F_SignedByIDNo]   VARCHAR (20)    NULL,
    [SignedDate]       DATE            NULL,
    [F_ImpCost]        DECIMAL (18, 2) NULL,
    [F_GSTCost]        DECIMAL (18, 2) NULL,
    [SignedByName_Imp] NVARCHAR (50)   NULL,
    [SignedByIDNo_Imp] VARCHAR (20)    NULL,
    [SignedByPos_Imp]  NVARCHAR (50)   NULL,
    [CreatedByUserId]  INT             NULL,
    [CreatedDT]        DATETIME        NULL,
    [EditedByUserId]   INT             NULL,
    [EditedDT]         DATETIME        NULL,
    CONSTRAINT [PK_RptSK] PRIMARY KEY CLUSTERED ([RptId] ASC)
);

