using System;
using System.Collections.Generic;

namespace AppReport.PTSDataModel
{
    public partial class RptLg
    {
        public int RptId { get; set; }
        public int? RptStatusId { get; set; }
        public string FCoName { get; set; }
        public string FCoRegNo { get; set; }
        public string FCoAdd1 { get; set; }
        public string FCoAdd2 { get; set; }
        public string FCoAdd3 { get; set; }
        public string FCoAdd4 { get; set; }
        public string FCoTel { get; set; }
        public string FCoFax { get; set; }
        public string FCoEmail { get; set; }
        public string FCoWebsite { get; set; }
        public string FCoLogo { get; set; }
        public int? RptY1 { get; set; }
        public int? RptY2 { get; set; }
        public DateTime? RptSdateY1 { get; set; }
        public DateTime? RptEdateY1 { get; set; }
        public DateTime? RptSdateY2 { get; set; }
        public DateTime? RptEdateY2 { get; set; }
        public DateTime? RptSdateY3 { get; set; }
        public DateTime? RptEdateY3 { get; set; }
        public string RefNo { get; set; }
        public DateTime? Ldate { get; set; }
        public string LrcptDept { get; set; }
        public string LrcptBr { get; set; }
        public string LrcptAdd1 { get; set; }
        public string LrcptAdd2 { get; set; }
        public string LrcptAdd3 { get; set; }
        public string LrcptAdd4 { get; set; }
        public string PbbcekNo { get; set; }
        public decimal? LicenseFee { get; set; }
        public string LocImpMY1 { get; set; }
        public string LocImpMY2 { get; set; }
        public string LocExpMY1 { get; set; }
        public string LocExpMY2 { get; set; }
        public int? SignedByEmpId { get; set; }
        public string SignedByPos { get; set; }
        public string SignedByName { get; set; }
        public DateTime? SignedDate { get; set; }
        public string AppByPos { get; set; }
        public string AppByName { get; set; }
        public string AppByIdno { get; set; }
        public string AppCoName { get; set; }
        public string AppAdd1 { get; set; }
        public string AppAdd2 { get; set; }
        public string AppAdd3 { get; set; }
        public string AppAdd4 { get; set; }
        public DateTime? AppDate { get; set; }
        public string BrcptDept { get; set; }
        public string BrcptBr { get; set; }
        public string BrcptAdd1 { get; set; }
        public string BrcptAdd2 { get; set; }
        public string BrcptAdd3 { get; set; }
        public string BrcptAdd4 { get; set; }
        public int? BsignedByEmpId { get; set; }
        public string BsignedByPos { get; set; }
        public string BsignedByName { get; set; }
        public string BsignedByIdno { get; set; }
        public string BsignedByAdd1 { get; set; }
        public string BsignedByAdd2 { get; set; }
        public string BsignedByAdd3 { get; set; }
        public string BsignedByAdd4 { get; set; }
        public string RptCoName { get; set; }
        public int? RptSignedByEmpId { get; set; }
        public string RptSignedByPos { get; set; }
        public string RptSignedByIdno { get; set; }
        public string RptSignedByName { get; set; }
        public string MfdGood { get; set; }
        public DateTime? MfdLicenseSdate { get; set; }
        public DateTime? MfdLicenseEdate { get; set; }
        public bool? IsChgCoName { get; set; }
        public bool? IsChgCoMember { get; set; }
        public bool? IsChgAddress { get; set; }
        public bool? IsChgFtyStr { get; set; }
        public bool? IsChgEq { get; set; }
        public decimal? FRmcost { get; set; }
        public decimal? BgtRmcost { get; set; }
        public decimal? FRdyGoodCost { get; set; }
        public decimal? BgtRdyGoodCost { get; set; }
        public decimal? FMktExpCost { get; set; }
        public decimal? MktExpRate { get; set; }
        public decimal? BgtMktExpCost { get; set; }
        public decimal? BgtMktExpRate { get; set; }
        public decimal? FLocalSalesCost { get; set; }
        public decimal? LocalSalesRate { get; set; }
        public decimal? BgtLocSalesCost { get; set; }
        public decimal? BgtLocSalesRate { get; set; }
        public string IpcRdc { get; set; }
        public string ValueAdded { get; set; }
        public string RepairSvc { get; set; }
        public string SparePart { get; set; }
        public decimal? FImpOpenBalWgtY1 { get; set; }
        public decimal? FImpOpenBalCostY1 { get; set; }
        public decimal? FImpImpRmwgtY1 { get; set; }
        public decimal? FImpImpRmcostY1 { get; set; }
        public decimal? FImpLocRmwgtY1 { get; set; }
        public decimal? FImpLocRmcostY1 { get; set; }
        public decimal? FImpUsedRmwgtY1 { get; set; }
        public decimal? FImpUsedRmcostY1 { get; set; }
        public decimal? FImpReturnedWgtY1 { get; set; }
        public decimal? FImpCloseBalWgtY1 { get; set; }
        public decimal? FImpCloseBalCostY1 { get; set; }
        public decimal? FImpOpenBalWgtY2 { get; set; }
        public decimal? FImpOpenBalCostY2 { get; set; }
        public decimal? FImpRmwgtY2 { get; set; }
        public decimal? FImpRmcostY2 { get; set; }
        public decimal? FImpLocRmwgtY2 { get; set; }
        public decimal? FImpLocRmcostY2 { get; set; }
        public decimal? FImpUsedRmwgtY2 { get; set; }
        public decimal? FImpUsedRmcostY2 { get; set; }
        public decimal? FImpReturnedWgtY2 { get; set; }
        public decimal? FImpCloseBalWgtY2 { get; set; }
        public decimal? FImpCloseBalCostY2 { get; set; }
        public decimal? FRdyCostY1 { get; set; }
        public decimal? FRdyDutyImpCostY1 { get; set; }
        public decimal? FRdyGstcostY1 { get; set; }
        public decimal? FRdyTaxCostY1 { get; set; }
        public decimal? FRdyCostY3 { get; set; }
        public decimal? FRdyDutyImpCostY3 { get; set; }
        public decimal? FRdyGstcostY3 { get; set; }
        public decimal? FRdyTaxCostY3 { get; set; }
        public decimal? FRdyStkCostY2 { get; set; }
        public decimal? FRdyDutyImpCostY2 { get; set; }
        public decimal? FRdyGstcostY2 { get; set; }
        public decimal? FRdyTaxCostY2 { get; set; }
        public int? FBgtQtyLoc { get; set; }
        public decimal? FBgtCostLoc { get; set; }
        public decimal? FBgtDutyImpCostLoc { get; set; }
        public decimal? FBgtGstcostLoc { get; set; }
        public decimal? FBgtTaxCostLoc { get; set; }
        public int? FBgtQtyImp { get; set; }
        public decimal? FBgtCostImp { get; set; }
        public decimal? FBgtDutyImpCostImp { get; set; }
        public decimal? FBgtGstcostImp { get; set; }
        public decimal? FBgtTaxCostImp { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? CreatedDt { get; set; }
        public int? EditedByUserId { get; set; }
        public DateTime? EditedDt { get; set; }
    }
}
